version: '3.5'

services:
  sps_db:
    container_name: sps_db
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bQ5UroNM9PqslBs}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-sps_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: on-failure

  sps_cache:
    container_name: sps_cache
    image: redis:7.2-rc3-alpine
    command: "redis-server --requirepass Password"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: on-failure

  sps_web_server:
    container_name: sps_web_server
    image: nginx:alpine
    volumes:
      - ./public/nginx/upload.conf:/etc/nginx/conf.d/upload.conf
      - ./public/assets:/usr/share/nginx/html/upload/
    ports:
      - "8080:80"
    restart: on-failure
