name: 'CI Workflow'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']
  push:
    branches: ['main']

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.1

      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run prisma:generate
      - run: pnpm run build

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.1

      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint

  security-scan:
    name: Semgrep PR Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/default
          generateSarif: true
          output: semgrep.sarif

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
